export const ActionTypes = {
    HANDLE_QUESTIONS_SUBMIT : "HANDLE_QUESTIONS_SUBMIT",
    HANDLE_QUESTIONS_CHANGE : "HANDLE_QUESTIONS_CHANGE",
    SELECT_DISPLAYED : "SELECT_DISPLAYED",
    RESET_APP  : 'RESET_APP'
}